#!/usr/bin/env python3
#ender here the path or the URL to the sound you want to play
def play_sound():
    sound =
    playsound(sound)

import sys
import os
from threading import Thread
from playsound import playsound

argument = sys.argv[1]
pkgname = sys.argv[2]

thread = Thread(target=play_sound)
thread.start()
os.system("sudo apt " + argument + " " + pkgname)
exit()
